{% set name = "rcedit" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/electron/rcedit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2a55a176fc11cc563cd827ef3f55a7afe2aa0dca1ecc8d8d53b1b5afd5cffa20
  patches:
    - 103-version.patch

build:
  skip: true  # [unix]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake

test:
  commands:
    - rcedit --help

about:
  home: https://github.com/electron/rcedit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line tool to edit resources of exe file on Windows.

extra:
  recipe-maintainers:
    - hmaarrfk
